config/routes.rb
TcfLabels::Application.routes.draw do

  resources :label_data_sets do
    resources :label_data
  end

  get "home/index"

  root :to => "label_data_sets#index"

end

app/controllers/label_data_controller.rb
class LabelDataController < ApplicationController
  # GET /label_data
  # GET /label_data.xml
  def index
    @label_data = LabelDatum.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @label_data }
    end
  end

  # GET /label_data/1
  # GET /label_data/1.xml
  def show
    @label_datum = LabelDatum.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @label_datum }
    end
  end

  # GET /label_data/new
  # GET /label_data/new.xml
  def new
    @label_datum = LabelDatum.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @label_datum }
    end
  end

  # GET /label_data/1/edit
  def edit
    @label_datum = LabelDatum.find(params[:id])
  end

  # POST /label_data
  # POST /label_data.xml
  def create
    @label_datum = LabelDatum.new(params[:label_datum])

    respond_to do |format|
      if @label_datum.save
        format.html { redirect_to(@label_datum, :notice => 'Label datum was successfully created.') }
        format.xml  { render :xml => @label_datum, :status => :created, :location => @label_datum }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @label_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /label_data/1
  # PUT /label_data/1.xml
  def update
    @label_datum = LabelDatum.find(params[:id])

    respond_to do |format|
      if @label_datum.update_attributes(params[:label_datum])
        format.html { redirect_to(@label_datum, :notice => 'Label datum was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @label_datum.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /label_data/1
  # DELETE /label_data/1.xml
  def destroy
    @label_datum = LabelDatum.find(params[:id])
    @label_datum.destroy

    respond_to do |format|
      format.html { redirect_to(label_data_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/label_data_helper.rb
module LabelDataHelper
  def empty_ness(str)
    str = str.to_s
    str.nil? || str.empty? ? raw('&nbsp;') : str
  end
end

app/views/label_data/_form.html.haml
= form_for @label_datum do |f|
  -if @label_datum.errors.any?
    #error_explanation
      %h2= "#{pluralize(@label_datum.errors.count, "error")} prohibited this label_datum from being saved:"
      %ul
        - @label_datum.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :field1
    = f.text_field :field1
  .field
    = f.label :field2
    = f.text_field :field2
  .field
    = f.label :field3
    = f.text_field :field3
  .field
    = f.label :field4
    = f.text_field :field4
  .field
    = f.label :field5
    = f.text_field :field5
  .field
    = f.label :field6
    = f.text_field :field6
  .field
    = f.label :field7
    = f.text_field :field7
  .field
    = f.label :field8
    = f.text_field :field8
  .field
    = f.label :field9
    = f.text_field :field9
  .field
    = f.label :field10
    = f.text_field :field10
  .field
    = f.label :field11
    = f.text_field :field11
  .field
    = f.label :field12
    = f.text_field :field12
  .field
    = f.label :label_data_set_id
    = f.text_field :label_data_set_id
  .actions
    = f.submit 'Save'

app/views/label_data/_label_datum.html.haml
- if ( label_datum_counter + 1 ) % 18 == 0 
  .label_space.lastcol.lastrow
    = render :partial => 'label_data/label_info', :locals => { :label_datum => label_datum }
- elsif ( label_datum_counter + 1 ) % 3 == 0 
  .label_space.lastcol
    = render :partial => 'label_data/label_info', :locals => { :label_datum => label_datum }
- else
  .label_space
    = render :partial => 'label_data/label_info', :locals => { :label_datum => label_datum }

app/views/label_data/_label_info.html.haml
.label
  .field1
    =  empty_ness label_datum.field1
  .field3
    =  empty_ness label_datum.field3
  %br
  - if label_datum.field5.length < 28 then
    .field5.shortname
      = label_datum.field5
  - elsif label_datum.field5.length < 36 then
    .field5
      = label_datum.field5
  - else
    .field5.longname
      = label_datum.field5
  %br
  .field9
    = empty_ness label_datum.field9
  %br
  .field10
    = label_datum.field10
  .field12
    = label_datum.field12

app/views/label_data/edit.html.haml
%h1 Editing label_datum

= render 'form'

= link_to 'Show', @label_datum
\|
= link_to 'Back', label_data_path

app/views/label_data/index.html.haml
%h1 Listing label_data

%table
  %tr
    %th Name
    %th Field1
    %th Field2
    %th Field3
    %th Field4
    %th Field5
    %th Field6
    %th Field7
    %th Field8
    %th Field9
    %th Field10
    %th Field11
    %th Field12
    %th Label data set
    %th
    %th
    %th

  - @label_data.each do |label_datum|
    %tr
      %td= label_datum.name
      %td= label_datum.field1
      %td= label_datum.field2
      %td= label_datum.field3
      %td= label_datum.field4
      %td= label_datum.field5
      %td= label_datum.field6
      %td= label_datum.field7
      %td= label_datum.field8
      %td= label_datum.field9
      %td= label_datum.field10
      %td= label_datum.field11
      %td= label_datum.field12
      %td= label_datum.label_data_set_id
      %td= link_to 'Show', label_datum
      %td= link_to 'Edit', edit_label_datum_path(label_datum)
      %td= link_to 'Destroy', label_datum, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Label datum', new_label_datum_path

app/views/label_data/new.html.haml
%h1 New label_datum

= render 'form'

= link_to 'Back', label_data_path

app/views/label_data/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @label_datum.name
%p
  %b Field1:
  = @label_datum.field1
%p
  %b Field2:
  = @label_datum.field2
%p
  %b Field3:
  = @label_datum.field3
%p
  %b Field4:
  = @label_datum.field4
%p
  %b Field5:
  = @label_datum.field5
%p
  %b Field6:
  = @label_datum.field6
%p
  %b Field7:
  = @label_datum.field7
%p
  %b Field8:
  = @label_datum.field8
%p
  %b Field9:
  = @label_datum.field9
%p
  %b Field10:
  = @label_datum.field10
%p
  %b Field11:
  = @label_datum.field11
%p
  %b Field12:
  = @label_datum.field12
%p
  %b Label data set:
  = @label_datum.label_data_set_id

= link_to 'Edit', edit_label_datum_path(@label_datum)
\|
= link_to 'Back', label_data_path